server:
   port: 8001
   
#security:
#   sessions: STATELESS # 设置session状态
#   basic:
#      enabled: true    # 启用SpringSecurity安全配置项
#   user:
#      name: bigBadEgg  # 认证用户名
#      password: 123    # 认证密码
#      role:            # 授权角色
#         - USER

mybatis:
   config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件路径
   type-aliases-package: com.ithm.entity               # 定义操作类所在包
   mapper-locations: classpath:mybatis/mapper/*.xml    # 映射文件
spring:
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource     # 配置数据源类型
      #driver-class-name: org.git.mm.mysql.Driver      # 配置MySQL驱动程序类
      Driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ithm8001        # 数据库连接地址
      username: root
      password: 123
      dbcp2:                                           # 数据库连接池配置
         min-idle: 5                                   # 最小连接数
         initial-size: 5                               # 初始化连接数
         max-total: 5                                  # 最大连接数
         max-wait-millis: 200                          # 最长等待时间
